#!/usr/bin/env bash
# generate-codebase-map.sh — Generates docs/05-design/CODEBASE-MAP.md
# Deterministic (no AI). Runs find on src/ and tests/, outputs a structured map.
# If src/ is empty (only .gitkeep), outputs "Greenfield" marker.

set -euo pipefail

SRC_DIR="${1:-src}"
TESTS_DIR="${2:-tests}"
OUTPUT_FILE="${3:-docs/05-design/CODEBASE-MAP.md}"
DATE=$(date -u '+%Y-%m-%d')

# Ensure output directory exists
mkdir -p "$(dirname "$OUTPUT_FILE")"

# Check if src/ has any real source files
src_files=$(find "$SRC_DIR" -type f \
  \( -name "*.py" -o -name "*.ts" -o -name "*.tsx" -o -name "*.js" -o -name "*.jsx" \
     -o -name "*.go" -o -name "*.rs" -o -name "*.java" -o -name "*.rb" -o -name "*.ex" \
     -o -name "*.cs" -o -name "*.kt" -o -name "*.swift" -o -name "*.dart" \
     -o -name "*.cpp" -o -name "*.c" -o -name "*.h" -o -name "*.hpp" \) \
  2>/dev/null || true)

if [ -z "$src_files" ]; then
  # Greenfield — no source files
  cat > "$OUTPUT_FILE" << EOF
# Codebase Map
<!-- Auto-generated by scripts/generate-codebase-map.sh. Do not edit manually. -->
<!-- Last updated: ${DATE} -->

**Status: Greenfield — no source files yet.**

When source code is added to \`src/\`, this file will be automatically regenerated
with directory structure, module listings, and test structure.
EOF
  echo "Generated greenfield CODEBASE-MAP.md"
  exit 0
fi

# Active codebase — generate full map
{
  echo "# Codebase Map"
  echo "<!-- Auto-generated by scripts/generate-codebase-map.sh. Do not edit manually. -->"
  echo "<!-- Last updated: ${DATE} -->"
  echo ""
  echo "## Directory Structure"
  echo ""
  echo '```'
  # Tree with depth limit of 4, showing only directories and source files
  if command -v tree &>/dev/null; then
    tree "$SRC_DIR" -L 4 --dirsfirst -I '__pycache__|node_modules|.git|*.pyc|dist|build' 2>/dev/null || \
      find "$SRC_DIR" -maxdepth 4 -type d 2>/dev/null | sort
  else
    find "$SRC_DIR" -maxdepth 4 -type d 2>/dev/null | sort
  fi
  echo '```'
  echo ""

  echo "## Modules"
  echo ""
  echo "| Directory | File Count | Languages |"
  echo "|---|---|---|"

  # List each directory under src/ that contains source files
  find "$SRC_DIR" -type f \
    \( -name "*.py" -o -name "*.ts" -o -name "*.tsx" -o -name "*.js" -o -name "*.jsx" \
       -o -name "*.go" -o -name "*.rs" -o -name "*.java" -o -name "*.rb" \) \
    2>/dev/null | \
    sed 's|/[^/]*$||' | sort -u | while IFS= read -r dir; do
      count=$(find "$dir" -maxdepth 1 -type f \
        \( -name "*.py" -o -name "*.ts" -o -name "*.tsx" -o -name "*.js" -o -name "*.jsx" \
           -o -name "*.go" -o -name "*.rs" -o -name "*.java" -o -name "*.rb" \) \
        2>/dev/null | wc -l | tr -d ' ')
      # Detect languages
      langs=""
      [ "$(find "$dir" -maxdepth 1 -name '*.py' 2>/dev/null | head -1)" ] && langs="${langs}Python "
      [ "$(find "$dir" -maxdepth 1 \( -name '*.ts' -o -name '*.tsx' \) 2>/dev/null | head -1)" ] && langs="${langs}TypeScript "
      [ "$(find "$dir" -maxdepth 1 \( -name '*.js' -o -name '*.jsx' \) 2>/dev/null | head -1)" ] && langs="${langs}JavaScript "
      [ "$(find "$dir" -maxdepth 1 -name '*.go' 2>/dev/null | head -1)" ] && langs="${langs}Go "
      [ "$(find "$dir" -maxdepth 1 -name '*.rs' 2>/dev/null | head -1)" ] && langs="${langs}Rust "
      [ "$(find "$dir" -maxdepth 1 -name '*.java' 2>/dev/null | head -1)" ] && langs="${langs}Java "
      [ "$(find "$dir" -maxdepth 1 -name '*.rb' 2>/dev/null | head -1)" ] && langs="${langs}Ruby "
      langs=$(echo "$langs" | xargs | tr ' ' ', ')
      echo "| \`${dir}\` | ${count} | ${langs} |"
    done

  echo ""
  echo "## Source Files"
  echo ""
  echo '```'
  echo "$src_files" | head -50 | sort
  file_count=$(echo "$src_files" | wc -l | tr -d ' ')
  if [ "$file_count" -gt 50 ]; then
    echo "... and $((file_count - 50)) more files"
  fi
  echo '```'
  echo ""

  echo "## Test Structure"
  echo ""
  test_files=$(find "$TESTS_DIR" -type f \
    \( -name "*.py" -o -name "*.ts" -o -name "*.tsx" -o -name "*.js" -o -name "*.jsx" \
       -o -name "*.spec.*" -o -name "*.test.*" \) \
    2>/dev/null || true)

  if [ -z "$test_files" ]; then
    echo "No test files found in \`${TESTS_DIR}/\`."
  else
    echo '```'
    if command -v tree &>/dev/null; then
      tree "$TESTS_DIR" -L 4 --dirsfirst -I '__pycache__|node_modules|.git|*.pyc' 2>/dev/null || \
        echo "$test_files" | head -30 | sort
    else
      echo "$test_files" | head -30 | sort
    fi
    echo '```'
  fi
} > "$OUTPUT_FILE"

echo "Generated CODEBASE-MAP.md ($(echo "$src_files" | wc -l | tr -d ' ') source files)"
